### ISSUE TITLE
Pulling but po not functional

### ISSUE THREAD

**Issue by fxbenard** [markoheijnen/grunt-glotpress#19]
Hey,

On windows your test.js dl the po and mo but see what I get for example in tabify-edit-screen-nl_NL.
Same for all languages

`{"translation_sets":[{"id":"1","name":"Dutch","slug":"default","project_id":"1","locale":"nl","current_count":"13","untranslated_count":0,"waiting_count":0,"fuzzy_count":0,"percent_translated":100,"wp_locale":"nl_NL","last_modified":"2013-09-26 17:12:22"},{"id":"2","name":"French (France)","slug":"default","project_id":"1","locale":"fr","current_count":"13","untranslated_count":0,"waiting_count":0,"fuzzy_count":0,"percent_translated":100,"wp_locale":"fr_FR","last_modified":"2013-09-26 17:12:30"},{"id":"3","name":"Serbian","slug":"default","project_id":"1","locale":"sr","current_count":"4","untranslated_count":9,"waiting_count":0,"fuzzy_count":0,"percent_translated":30,"wp_locale":"sr_RS","last_modified":"2013-09-26 17:12:41"},{"id":"4","name":"German","slug":"default","project_id":"1","locale":"de","current_count":"3","untranslated_count":10,"waiting_count":0,"fuzzy_count":0,"percent_translated":23,"wp_locale":"de_DE","last_modified":"2013-02-01 17:31:40"},{"id":"114","name":"My Translation","slug":"my","project_id":"1","locale":"bg","current_count":0,"untranslated_count":13,"waiting_count":0,"fuzzy_count":0,"percent_translated":0,"wp_locale":"bg_BG","last_modified":false}],"sub_projects":[]}`

**Comment by markoheijnen** [comment]
Oops, my bad. Rewrote all and I should have tested it after that "one more change". Good luck there is ticket #20 ;)

**Comment by fxbenard** [comment]
Works like a charm, thanks
