### ISSUE TITLE
Not pulling all .po files

### ISSUE THREAD

**Issue by fxbenard** [markoheijnen/grunt-glotpress#21]
I can't figure why some po files aren't pulled

To reproduce something you're concern about let's take GlotPress ;)
`    glotpress_download: {
    		core: {
      			options: {
       				domainPath: 'glotpress',
        				url: 'https://translate.wordpress.org',
        				slug: 'glotpress/dev',
        				textdomain: 'glotpress',
        			}
        		},
        	},`

Check it out fr_FR is missing for example- Did you setup a minimum percentage?

**Comment by markoheijnen** [comment]
minimum percentage by default is 30%. I'm fine with having that false.

**Comment by fxbenard** [comment]
Ok thanks for the confirmation - Need to make the French translation validated then ;)
